#spring:
#  application:
#    name: service-consumer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8888
#feign:
#  sentinel:
#    enabled: true
#server:
#  port: 8080
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"